// Code generated by MockGen. DO NOT EDIT.
// Source: user.trpc.go
//
// Generated by this command:
//
//	mockgen -destination=user_mock.go -package=user --source=user.trpc.go -self_package=github.com/ustcLyric/trpcprotocol/user
//

// Package user is a generated GoMock package.
package user

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	client "trpc.group/trpc-go/trpc-go/client"
)

// MockUserServiceService is a mock of UserServiceService interface.
type MockUserServiceService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceServiceMockRecorder is the mock recorder for MockUserServiceService.
type MockUserServiceServiceMockRecorder struct {
	mock *MockUserServiceService
}

// NewMockUserServiceService creates a new mock instance.
func NewMockUserServiceService(ctrl *gomock.Controller) *MockUserServiceService {
	mock := &MockUserServiceService{ctrl: ctrl}
	mock.recorder = &MockUserServiceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServiceService) EXPECT() *MockUserServiceServiceMockRecorder {
	return m.recorder
}

// GetUserInfo mocks base method.
func (m *MockUserServiceService) GetUserInfo(ctx context.Context, req *GetUserInfoReq) (*GetUserInfoReq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", ctx, req)
	ret0, _ := ret[0].(*GetUserInfoReq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockUserServiceServiceMockRecorder) GetUserInfo(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockUserServiceService)(nil).GetUserInfo), ctx, req)
}

// Hello mocks base method.
func (m *MockUserServiceService) Hello(ctx context.Context, req *GetUserInfoReq) (*GetUserInfoReq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hello", ctx, req)
	ret0, _ := ret[0].(*GetUserInfoReq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hello indicates an expected call of Hello.
func (mr *MockUserServiceServiceMockRecorder) Hello(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hello", reflect.TypeOf((*MockUserServiceService)(nil).Hello), ctx, req)
}

// Hello1 mocks base method.
func (m *MockUserServiceService) Hello1(ctx context.Context, req *GetUserInfoReq) (*GetUserInfoReq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hello1", ctx, req)
	ret0, _ := ret[0].(*GetUserInfoReq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hello1 indicates an expected call of Hello1.
func (mr *MockUserServiceServiceMockRecorder) Hello1(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hello1", reflect.TypeOf((*MockUserServiceService)(nil).Hello1), ctx, req)
}

// MockUserServiceClientProxy is a mock of UserServiceClientProxy interface.
type MockUserServiceClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceClientProxyMockRecorder
	isgomock struct{}
}

// MockUserServiceClientProxyMockRecorder is the mock recorder for MockUserServiceClientProxy.
type MockUserServiceClientProxyMockRecorder struct {
	mock *MockUserServiceClientProxy
}

// NewMockUserServiceClientProxy creates a new mock instance.
func NewMockUserServiceClientProxy(ctrl *gomock.Controller) *MockUserServiceClientProxy {
	mock := &MockUserServiceClientProxy{ctrl: ctrl}
	mock.recorder = &MockUserServiceClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServiceClientProxy) EXPECT() *MockUserServiceClientProxyMockRecorder {
	return m.recorder
}

// GetUserInfo mocks base method.
func (m *MockUserServiceClientProxy) GetUserInfo(ctx context.Context, req *GetUserInfoReq, opts ...client.Option) (*GetUserInfoReq, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserInfo", varargs...)
	ret0, _ := ret[0].(*GetUserInfoReq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockUserServiceClientProxyMockRecorder) GetUserInfo(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockUserServiceClientProxy)(nil).GetUserInfo), varargs...)
}

// Hello mocks base method.
func (m *MockUserServiceClientProxy) Hello(ctx context.Context, req *GetUserInfoReq, opts ...client.Option) (*GetUserInfoReq, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Hello", varargs...)
	ret0, _ := ret[0].(*GetUserInfoReq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hello indicates an expected call of Hello.
func (mr *MockUserServiceClientProxyMockRecorder) Hello(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hello", reflect.TypeOf((*MockUserServiceClientProxy)(nil).Hello), varargs...)
}

// Hello1 mocks base method.
func (m *MockUserServiceClientProxy) Hello1(ctx context.Context, req *GetUserInfoReq, opts ...client.Option) (*GetUserInfoReq, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Hello1", varargs...)
	ret0, _ := ret[0].(*GetUserInfoReq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hello1 indicates an expected call of Hello1.
func (mr *MockUserServiceClientProxyMockRecorder) Hello1(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hello1", reflect.TypeOf((*MockUserServiceClientProxy)(nil).Hello1), varargs...)
}
